default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: development_news

test:
  <<: *default
  database: test_news

production:
  <<: *default
  database: production_news
