default: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *defaults
  database: development_news

test:
  <<: *defaults
  database: test_news

production:
  <<: *defaults
  database: production_news
