default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: db/development_news.sqlite3

test:
  <<: *default
  database: db/test_news.sqlite3

production:
  <<: *default
  database: db/production_news.sqlite3
